### ISSUE TITLE
White/red colors that make no sense

### ISSUE THREAD

**Issue by shavitush** [jesseweed/seti-syntax#133]
![atom_2016-07-16_06-34-10](https://cloud.githubusercontent.com/assets/3672466/16892566/67ac6fde-4b1f-11e6-8389-d9166455ddca.png)

I really love the Seti syntax theme, but this one really triggers me.. I'm talking about the different colors in the braces after `function`. Is this intentional? The file syntax is C++ and it also happens with [SourcePawn](https://github.com/50Wliu/language-sourcepawn). Doesn't seem to happen with C# or Java.

**Comment by Alhadis** [comment]
Hi @shavitush,

Whenever this happens, it's usually because of an error with the grammar package that's highlighting the code. In this case, the appropriate thing to do is to file an issue to the grammar's upstream repository (which would have been [`atom/language-c`](https://github.com/atom/language-c) for C++). This was already fixed long ago, however:

<img src="https://user-images.githubusercontent.com/2346707/28499221-d2fcea8a-6ff3-11e7-9194-9e5758de4e02.png" width="221" alt="Figure 1" />

So it's safe to close this issue and mark it resolved. ;-)

**PS:** If you're unhappy with how a syntax theme colours your code, you can always tweak it with your [user stylesheet](https://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks):

~~~less
.syntax--source.syntax--cpp {
	.syntax--punctuation.syntax--bracket.syntax--round {
		color: #f00; /* Styling here */
	}
}
~~~

**Comment by shavitush** [comment]
A bit old (old enough that I don't use Atom anymore) - but thank you!
