### ISSUE TITLE
seti-syntax package breaks apm upgrade mechanism

### ISSUE THREAD

**Issue by OClyde** [jesseweed/seti-syntax#145]
Hey there, just switched to seti-syntax today and got to say: It's really really great. However, after the installation I recognized, that I wasn't able to use the `apm upgrade` command anymore as it simply returns `undefined`.

Tracked it down to the seti-syntax package:
```
~ $ apm upgrade
undefined
~ $ apm deinstall seti-syntax
Uninstalling seti-syntax ✓
~ $ apm upgrade
Package Updates Available (0)
└── (empty)
~ $
~ $
~ $ apm --version
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.10
git 2.8.4
```

Just wanted to be sure to report this in case anyone else is encountering this problem.
Additionally, if you need any further information, don't hesitate to ask!

**Comment by pjenx** [comment]
+1 Came here to report the same issue. I installed the most recent update of seti-syntax, and experienced the same problem. Haven't done any debugging, but it happened the moment seti-syntax was updated: atom cannot successfully search for updates. Settings>Update returns undefined. I also noticed that seti-syntax is no longer selectable in the Sytax Theme dropdown, and doesn't appear under Installed Themes, (thus can't be uninstalled in the gui) though it is still in the config folder.

**Comment by jriesen** [comment]
This same problem is referenced in https://github.com/atom/atom/issues/13790 

I tried turning off Dynamic Theme (basically the only useful configuration option) but it didn't do anything; I think it's a problem with the theme itself.

I reverted to version 1.0.1 and it seems to work properly:
`apm install seti-syntax@1.0.1`

**Comment by joaufi** [comment]
[atom/apm #620](https://github.com/atom/apm/issues/620) is the issue thread on apm for this same problem.

**Comment by claylevering** [comment]
Just leaving a note after finding the same issue, thank you to @jriesen for the workaround which is functioning great!

**Comment by itsnotvalid** [comment]
The strange case for `seti-syntax` is that, even the version in package index is in the form of git package.

**Comment by faddah** [comment]
Hello,

Can this please re-opened, @jesseweed, please? I am seeing the exact same thing with both `seti-ui` and `seti-syntax` installed, and I especially like using `seti-syntax`. 

my set-up is:

Mac OS v10.12.4
Atom v1.16.0

and from `apm version` on the command line —

```
$ apm --version
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.10
git 2.11.0
```
`
with `seti-ui` and `seti-syntax` installed, either from within Atom > Settings > Updates or from the command line with `apm update`, i get —

```
$ apm update
undefined
```

... everytime. the moment i remove seti-ui` and `seti-syntax`, updates, both from within the Atom editor app and from the command line, work fine.

can this please be updated so that all your seti theme packages work with the apm update in the current Atom 1.16.0, please?

i will also put this over in jesseweed/seti-ui#381 , which is the same issue for seti-ui.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by jriesen** [comment]
FYI, I think there's something peculiar with your setup -- I am also running OSX 10.12.4 and Atom 1.16.0, using seti-ui and seti-syntax, and this problem was resolved for me back in early March.  I am running seti-ui@1.7.0 and seti-syntax@1.1.3, which are the latest versions.  Checking for updates both in Atom and at the command line with `apm update` work fine for me.

**Comment by faddah** [comment]
@jriesen @jesseweed - ok, i did what you said and that is working for me now, with the new seti-ui@1.7.0 & seti-syntax@1.1.3 running now and, after restart, Atom editor updates working fine. so ok to leave it closed, but I would suggest adding to your README.md with notes that if they had the earlier versions and are running into the update problem —

1. delete old versions of seti-ui & seti-syntax from Atom themes
2. restart Atom
3. install the latest seti-ui@1.7.0 & seti-syntax@1.1.3 in Atom > Settings > Install
4. restart Atom & test Atom > Settings > Updates to make sure it working o.k.

That is my suggestion for the README.md here. I will also post this in jesseweed/seti-ui#381.

best,

—  faddah
      portland, oregon, u.s.a.

**Comment by ghost** [comment]
NS configuration
